### ISSUE TITLE
offline recognizer似乎没有使用gpu

### ISSUE THREAD

**Issue by DeoLeung** [k2-fsa/sherpa-onnx#1895]
```python
self.offline_recognizer_model = sherpa_onnx.OfflineRecognizer.from_fire_red_asr(
              encoder_path,
              decoder_path,
              tokens_path,
              provider=settings.execution_provider,
              num_threads=settings.num_threads,
          )
```
设置了provider为cuda, threads为16

推理的时候, cpu确实跑到16了, 但是gpu似乎没有动作, 感觉速度是比较慢的, 如何确定模型真实跑在gpu上呢?

另外丢了一个大的语音文件, 一旦failed allocate后, 显存就不释放, 然后需要硬重启了, 该如何处理?
```bash
asr-firered-1  |   File "/usr/local/lib/python3.12/dist-packages/sherpa_onnx/offline_recognizer.py", line 882, in decode_stream
asr-firered-1  |     self.recognizer.decode_stream(s)
asr-firered-1  | RuntimeError: Non-zero status code returned while running Split node. Name:'Split' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 8908800
```

**Comment by csukuangfj** [comment]
请描述复现步骤。比如，你是如何安装 sherpa-onnx 的.

**Comment by csukuangfj** [comment]
你是否看过 sherpa-onnx 的文档，如何安装 gpu 版本的 sherpa-onnx?

是否搜索过 sherpa-onnx 的 issue, 看大家是如何用 gpu 版本的 sherpa-onnx?

**Comment by DeoLeung** [comment]
我使用下面的docker
```
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
WORKDIR ${target}
ARG DEBIAN_FRONTEND=noninteractive
ADD https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py
RUN echo "deb http://abc/repository/apt-ubuntu/ jammy main universe"  > /etc/apt/sources.list && \
  echo "deb http://abc/repository/deadsnakes-ppa-ubuntu/ jammy main"  >> /etc/apt/sources.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA6932366A755776 && \
  apt update && \
  apt install -y --no-install-recommends libasound2 python3.12 && \
  cat /tmp/get-pip.py | python3.12 && \
  pip3.12 install --no-cache-dir -i ${PYPI} poetry==2.0.1 && \
  poetry config virtualenvs.create false

ADD .../sherpa/poetry.lock ${target}/

RUN poetry install --no-cache --no-root --with gpu

RUN python3.12 -m compileall ${target}
CMD ["python3.12", "server.py"]
EXPOSE 18913
```
版本是
```toml
[tool.poetry.dependencies]
av = "^14.0.1"
betterproto = "v2.0.0b7"
grpclib = {version = ">=0.4.7", extras = ["protobuf"]}
numpy = ">2"
pydantic-settings = ">=2.0.3"
python = ">=3.11.0,<3.13"

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
sherpa-onnx = {version = "1.10.45+cuda", source = "k2-fsa"}

[[tool.poetry.source]]
name = "k2-fsa"
url = "https://k2-fsa.github.io/sherpa/onnx/cuda-cn.html"
```
版本应该对上了, 参考了[doc](https://k2-fsa.github.io/sherpa/onnx/python/install.html#method-2-from-pre-compiled-wheels-cpu-cuda)
